### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ChrLackner** [sizmailov/pybind11-stubgen#1]
Hi, I would like to build upon that code base. I would be willing to commit features/improvements if I do some. Could you license it under some terms?
Best Christopher

**Comment by sizmailov** [comment]
Hi, thanks for feedback! This small tool is far from perfect shape so PR/issues are very welcome) 
I think it would be appropriate to license `pybind11-stubgen` under BSD just as `pybind11`.
I'll add LICENSE file and update PYPI package shortly.

**Comment by ChrLackner** [comment]
Hi, yes I know, but I was searching for this and wanted to start it myself already. But if you already started and I can build upon it that would be nice ;) I'll add pull requests of course.
