### ISSUE TITLE
Missing support for py::sequence types

### ISSUE THREAD

**Issue by SimonHeim** [sizmailov/pybind11-stubgen#105]
My Pybind11 wrapper uses the `py::sequence` protocol in various function declarations.

Similar to `list` and `dict`, these render to `sequence` in the newly generated stubfiles. However, unlike `list` and `dict`, `sequence` is not a reserved Python keyword. I think `py::sequence` should correspond to `collections.abc.Sequence`.

**Comment by sizmailov** [comment]
Hi! 

Thanks for the report. 
I've added the replacement `sequence` -> `typing.Sequence` in #106

**Comment by SimonHeim** [comment]
Thanks for the quick turnaround @sizmailov!
