### ISSUE TITLE
docstrings with c++11 string literals

### ISSUE THREAD

**Issue by kreuzberger** [sizmailov/pybind11-stubgen#11]
using c++11 string literals in docstrings seems not supported, gives a warning about empty docstrings.

e.g.
`.def("hello", &hello, R"-(
  help for function help
  )-"
`

**Comment by sizmailov** [comment]
The library does nothing with c++ sources, it analyses complied binaries. Anyway I checked it, and didn't reproduce.

Please provide minimal reproducible example, including module code, build steps and generated `.pyi` file

**Comment by kreuzberger** [comment]
I tested it against the pybind11 module and the stub file generator seems right, the __doc__ is empty in this cases.
I check and generate an issue against pybind11 if required. Thanks for support

**Comment by sizmailov** [comment]
No problems :)

**Comment by kreuzberger** [comment]
Hmm, retested it again with some modifications.
I have output from  Python console and from from pybind11_stubgen debug output

Python 3.6.3 (default, Aug 28 2019, 11:20:03) 
[GCC 7.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import viewbase
>>> dir(viewbase)
['KEYBOARDMODIFIER', 'ViewBase', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__']
>>> viewbase.ViewBase.minimize.__doc__
'minimize(self: viewbase.ViewBase) -> None\n\n\n                      .. py:method:: minimize()\n\n                         minimize the view to the task bar\n                      \n'
>>> viewbase.minimize.__doc__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'viewbase' has no attribute 'minimize'
>>> quit()


python3 -m pybind11_stubgen --log-level DEBUG viewbase
{__init__.py:506} INFO - Parsing 'viewbase' module
{__init__.py:439} WARNING - Unknown member ALT type : `<class 'viewbase.KEYBOARDMODIFIER'>` 
{__init__.py:439} WARNING - Unknown member CONTROL type : `<class 'viewbase.KEYBOARDMODIFIER'>` 
{__init__.py:439} WARNING - Unknown member NO type : `<class 'viewbase.KEYBOARDMODIFIER'>` 
{__init__.py:439} WARNING - Unknown member SHIFT type : `<class 'viewbase.KEYBOARDMODIFIER'>` 
{__init__.py:439} WARNING - Unknown member __members__ type : `<class 'dict'>` 
{__init__.py:628} INFO - mkdir `viewbase-stubs`
{__init__.py:361} DEBUG - Docstring is empty for 'viewbase.block'
{__init__.py:361} DEBUG - Docstring is empty for 'viewbase.close'
{__init__.py:361} DEBUG - Docstring is empty for 'viewbase.foreground'
{__init__.py:361} DEBUG - Docstring is empty for 'viewbase.get'
{__init__.py:361} DEBUG - Docstring is empty for 'viewbase.id'
{__init__.py:361} DEBUG - Docstring is empty for 'viewbase.keys'
{__init__.py:361} DEBUG - Docstring is empty for 'viewbase.maximize'
{__init__.py:361} DEBUG - Docstring is empty for 'viewbase.minimize'
{__init__.py:361} DEBUG - Docstring is empty for 'viewbase.normal'
{__init__.py:361} DEBUG - Docstring is empty for 'viewbase.set'
{__init__.py:361} DEBUG - Docstring is empty for 'viewbase.type'
{__init__.py:361} DEBUG - Docstring is empty for 'viewbase.update'

**Comment by sizmailov** [comment]
Can you share minimal C++ code with `KEYBOARDMODIFIER` and it's bindings?

**Comment by kreuzberger** [comment]
ignore the enum, different problem

**Comment by kreuzberger** [comment]
I added the enum issue to the minimum example, cause it generates a warning. maybe related to other issues :-)

[test_demo_1.zip](https://github.com/sizmailov/pybind11-stubgen/files/3565690/test_demo_1.zip)

**Comment by sizmailov** [comment]
Closed by 5ed98a3

**Comment by sizmailov** [comment]
@kreuzberger Please confirm that current master fixes the problem. Also file new issue if you find any problems with enums.

**Comment by kreuzberger** [comment]
tested with master and the warnings and debug issues were removed.
Still issue existing with overloads of functions, see new overload "minimize" in Class A in the attached examples
[python.zip](https://github.com/sizmailov/pybind11-stubgen/files/3566086/python.zip)

**Comment by sizmailov** [comment]
What is wrong with overloaded functions?

**Comment by kreuzberger** [comment]
generating stubfile for target test_demo_pymodule
[2019-09-02 15:38:14,319] {__init__.py:509} INFO - Parsing 'test_demo' module
[2019-09-02 15:38:14,343] {__init__.py:360} DEBUG - Docstring is empty for 'test_demo.minimize'

The real python docstring:

```
>>> import test_demo
>>> test_demo.A.minimize.__doc__
'minimize(*args, **kwargs)\nOverloaded function.\n\n1. minimize(self: test_demo.A) -> None\n\n2. minimize(self: test_demo.A, arg0: bool) -> None\n'
>>> 

```

**Comment by kreuzberger** [comment]
maybe the second methods gets an empty docstring from pybind?

**Comment by sizmailov** [comment]
No, this behavior is intended. You have 

```python
    @overload
    def minimize(self, arg0: bool) -> None: 
        pass
    @overload
    def minimize(self) -> None: ...
```
instead of 
```python
    def minimize(self, *args, **kwargs) -> Any:
    """Overloaded function.

1. minimize(self: test_demo.A) -> None

2. minimize(self: test_demo.A, arg0: bool) -> None
"""
```
