### ISSUE TITLE
import directive ignored

### ISSUE THREAD

**Issue by kreuzberger** [sizmailov/pybind11-stubgen#12]
When a pybind11 module is depending on another module, its required to add a line
py::import::module

in a module function definition i add an object of types of this module to the module

py::module::import("mytype")
m.add_object("name", py::cast(new mytype::MyType()))

This seems to work from pybind11 view, but my stub file is now missing an import of module mytype

WorkAround:
generate a dummy class as inheritance of MyType and add it to the module
py::class_<Dummy, mytype::MyType>(m ,"Dummy")
generates an import in the stub file

**Comment by sizmailov** [comment]
I think bare `py::module::import("mytype")` should produce and import statement, while the next one should for sure:

```C++
m.add_object("itertools", py::module::import("itertools"));
```

Same applies when attribute type is a type from imported module.

**Comment by kreuzberger** [comment]
Attached an extension from my example, no import on test_demo_import is generated in test_demo
[python.zip](https://github.com/sizmailov/pybind11-stubgen/files/3566080/python.zip)
