### ISSUE TITLE
Upgrade pybind11-stubgen crash stubs generation

### ISSUE THREAD

**Issue by nyckmaia** [sizmailov/pybind11-stubgen#120]
Hi, I have a C++/Pybind11 project in which I'am using `pybind11-stubgen` locally and also in Github actions to generate my Python stubs.

Topic 01: v0.16.2 + Old Syntax
---------------------------------
I was using the `pybind11-stubgen` version `v0.16.2` and everthing was working good!

In my Python script to generate the stubs, I was using this line below:
```
genStubsCommand = f"pybind11-stubgen maialib.maiacore --output-dir={stubsPath} --ignore-invalid=all --no-setup-py"
```
- This line on version `v0.16.2` generates all stubs on Windows, Linux and OSX without any errors.
- But when I try to use my module on VS Code, it show the stubs only in Windows and OSX machines.

**Question 1: Why I don't get the VS Code autocomple (stubs) inside the WSL (Linux) environment?**

Topic 02: v1.1.0 + New Syntax
---------------------------------
Well, after that, today I tried to use the lasted versio of `pybind11-stubgen`. The `v1.1.0`.
To do so, I have to change the line above to remove deprecated arguments.
The new line (new syntax) is below:
```
genStubsCommand = f"pybind11-stubgen maialib.maiacore --output-dir={stubsPath} --print-invalid-expressions-as-is --ignore-all-errors"
```
- This line on version `v0.16.2` generates all stubs on Windows, Linux and OSX without any errors.
- But when I try to use my module on VS Code, it does not works in any system.

**Question 2: Why I don't get the VS Code autocomple (stubs) in any operational system Python enviroment?**

Topic 03: [ERROR 'json']
--------------------------
Using the `v1.1.0`, if I remove the `--ignore-all-errors` I got a single line output saying that `pybind11-stubgen` does not recognize the type 'json'.
Yes, I'am using the `nlohmann::json` ([link here](https://github.com/nlohmann/json)) as input argument of many functions of my module. It was working good on `v0.16.2`.

**Question 3: What is the problem with json?**

Systems:
- Windows 11 x64, Mac OSX 10.15.7, Linux (WSL) 20.04
- Python Kernel: 3.8, 3.9 and 3.10
- VS Code 1.81.1 (on all 3 systems)
- VS Code extension:
  - Python v2023.14.0
  - Pylance v2023.8.40

Could you help me?

Thank you,

**Comment by sizmailov** [comment]
I don't use Windows, VSCode, or WSL, so I can't answer the questions on those topics.

> pybind11-stubgen does not recognize the type 'json'

Now `pybind11-stubgen` tries to resolve the names used in the output `*.pyi` files to add necessary import statements. Most likely your module uses a json object as argument/return value, but never defines what `json` is. If you run `mypy` on generated stubs it should provide a similar error.

It would be more helpful if you frame the questions in a smaller context with a minimal reproducible example.
