### ISSUE TITLE
Submodules no longer build the correct file structure

### ISSUE THREAD

**Issue by pvarin-figure** [sizmailov/pybind11-stubgen#135]
Previously the command
```bash
pybind11-stubgen module1.module2.module3
```
would create the directory structure
```
module1/module2/module3/__init__.pyi
```
Now it creates a single directory with the following name:
```
module1.module2.module3/__init__pyi
```

Is this the intended behavior in the new release?

**Comment by sizmailov** [comment]
Thanks for catching this!
