### ISSUE TITLE
This works fine with python 2.7

### ISSUE THREAD

**Issue by MatthijsBurgh** [sizmailov/pybind11-stubgen#14]
Just so you know, I tested this with Python 2.7 and didn't experience any issues

**Comment by sizmailov** [comment]
Thanks! 

Actually I did some tweaks to be compatible with python2.7 a while ago, but didn't update the README. Partially because I'm a bit lazy, partially because I didn't want to state python2.7 support. 

I'll update README to be more precise about python2 support.
