### ISSUE TITLE
Error message only references type, not specific function

### ISSUE THREAD

**Issue by virtuald** [sizmailov/pybind11-stubgen#164]
Using 2.3.1, I'm seeing error messages like so:

```
pybind11_stubgen - [  ERROR] In ntcore._ntcore.Topic : Can't find/import 'json'
pybind11_stubgen - [  ERROR] In ntcore._ntcore.TopicInfo : Can't find/import 'json'
pybind11_stubgen - [  ERROR] In ntcore._ntcore.TopicInfo : Can't find/import 'NT_Type'
```

But the error is actually one of the methods (in this case `ntcore._ntcore.Topic.publishEx`)... which is annoying to figure out if there are a lot of methods. Pretty sure it used to print out the method name?

This should be a pretty straightforward thing to reproduce, but if it isn't I can make a test case to show it.

**Comment by sizmailov** [comment]
Thanks for the report!
I've updated the error message to include the function/method name.
