### ISSUE TITLE
enum warning doesn't tell you where it's coming from

### ISSUE THREAD

**Issue by virtuald** [sizmailov/pybind11-stubgen#170]
```
pybind11_stubgen - [WARNING] Enum-like str representations were found with no matching mapping to the enum class location.
Use `--enum-class-locations` to specify full path to the following enum(s):
```

... not sure which functions are generating the warnings, and our packages are fairly large?

**Comment by virtuald** [comment]
But also, I've been really happy with the new improvements in stubgen, it's catching a lot more stuff that will hopefully result in better type checking :)

**Comment by sizmailov** [comment]
This is just a "helper" message. The actual errors that trigger this warning should be above, and should look like this:

https://github.com/sizmailov/pybind11-stubgen/blob/c34105aae8a35bb41554c97efead4744c1efdc35/tests/demo.errors.stderr.txt#L1-L2

**Comment by virtuald** [comment]
I'm not seeing those errors. Is there a flag? I'm doing...

```
    # Generate pyi modules
    out = cfg["out"]
    for stub in cfg["stubs"]:
        sys.argv = [
            "<dummy>",
            "--exit-code",
            "--ignore-invalid-expressions=<.*>",
            "--root-suffix=",
            "-o",
            out,
            stub,
        ]

        pybind11_stubgen.main()
```

**Comment by virtuald** [comment]
Oh I see, my ignore invalid expressions is going to ignore them.

**Comment by sizmailov** [comment]
It's a bug, If you ignore the expressions, the warning should not appear.
