### ISSUE TITLE
Failing to fully resolve classes?

### ISSUE THREAD

**Issue by ringohoffman** [sizmailov/pybind11-stubgen#182]
When I run `pybind11-stubgen` on [`taichi`](https://github.com/taichi-dev/taichi),

```console
$ pybind11-stubgen taichi._lib.core.taichi_python -o python
```
It seems to fail on expressions that do have corresponding `pybind11-stubgen`-generated class definitions. For example:

```python
class ASTBuilder:
    def begin_frontend_struct_for_on_external_tensor(self, arg0: taichi::lang::ExprGroup, arg1: taichi::lang::Expr, arg2: DebugInfo) -> None:
        ...
    def begin_frontend_struct_for_on_snode(self, arg0: taichi::lang::ExprGroup, arg1: taichi::lang::SNode, arg2: DebugInfo) -> None:
        ...
class ExprGroup:
    def __init__(self) -> None:
        ...
    def push_back(self, arg0: Expr) -> None:
        ...
    def size(self) -> int:
        ...
```

Is this a problem in my configuration?

**Comment by ringohoffman** [comment]
Ah... I think these are the result of failures to resolve these type expressions...

**Comment by ringohoffman** [comment]
Thanks! Moving all the `py::class_` declarations to the top was a super easy fix.

By the way... I did see something that might be unexpected. `Kernel` resolved correctly in a different method of this same class, but in the `Callable`, `Kernel` is left fully specified.

```python
class Program:
    def compile_kernel(self, arg0: CompileConfig, arg1: DeviceCapabilityConfig, arg2: Kernel) -> CompiledKernelData:
        ...
    def create_kernel(self, arg0: typing.Callable[[taichi._lib.core.taichi_python.Kernel], None], arg1: str, arg2: AutodiffMode) -> Kernel:
        ...
```

What could be causing this, do you think?

**Comment by sizmailov** [comment]
Could you share the corresponding functions docstrings?

**Comment by ringohoffman** [comment]
I'm not sure what you mean by docstring.

Here is the declaration of [`create_kernel`](https://github.com/taichi-dev/taichi/blob/bcd623fddccde980a01c2a9bb4facb56862cc26e/taichi/python/export_lang.cpp#L405-L412). It looks like a lambda function. Could that be the source of the issue?

Here is [`compile_kernel`](https://github.com/taichi-dev/taichi/blob/bcd623fddccde980a01c2a9bb4facb56862cc26e/taichi/program/program.cpp#L178-L188).

**Comment by sizmailov** [comment]
I mean the runtime `__doc__` property, e.g. `Program.compile_kernel.__doc__`

**Comment by ringohoffman** [comment]
```python
'compile_kernel(self: taichi._lib.core.taichi_python.Program, arg0: taichi._lib.core.taichi_python.CompileConfig, arg1: taichi._lib.core.taichi_python.DeviceCapabilityConfig, arg2: taichi._lib.core.taichi_python.Kernel) -> taichi._lib.core.taichi_python.CompiledKernelData\n'
```

```python
'create_kernel(self: taichi._lib.core.taichi_python.Program, arg0: Callable[[taichi._lib.core.taichi_python.Kernel], None], arg1: str, arg2: taichi._lib.core.taichi_python.AutodiffMode) -> taichi._lib.core.taichi_python.Kernel\n'
```
