### ISSUE TITLE
Missing wheels for newer releases

### ISSUE THREAD

**Issue by Teebor-Choka** [sizmailov/pybind11-stubgen#193]
When building wheel artifacts from packages depending on the `pybind11-stubgen` project using pyproject.toml it is not possible to use the recent versions due to missing wheels.

## Error
It appears as though earlier versions had the wheel published
> ERROR: Could not find a version that satisfies the requirement pybind11-stubgen==2.4 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.1.0, 0.1.0.post1, 0.2.0, 0.2.1, 0.2.2, 0.2.2.post1, 0.3.0, 0.3.1, 0.3.1.post1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.4.0, 0.5.0, 0.6.0, 0.6.1, 0.6.1.post1, 0.6.2, 0.7.0, 0.7.1, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.8.5, 0.8.6, 0.8.7, 0.8.8, 0.9, 0.9.1, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.10.4, 0.10.5, 0.11.0, 0.12.0, 0.13.0, 0.14.0, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.16.2)

## Remedy
Build and publish wheels at pypi (e.g. using https://github.com/pypa/cibuildwheel)

**Comment by sizmailov** [comment]
Wheels are there. Probably, you are on an unsupported python version.

**Comment by Teebor-Choka** [comment]
What is the least supported Python version for `pybind11-stubgen` version 2.4 wheels?
