### ISSUE TITLE
output is not deterministic

### ISSUE THREAD

**Issue by tgpfeiffer** [sizmailov/pybind11-stubgen#21]
Every time I run `pybind11-stubgen` the output file is different, i.e., method order changes. In my CI runs I would like to check that the latest version for my pybind module is committed, ideally with something like `pybind11-stubgen ... && git diff --exit-code`, but that does not work if the file changes every time.

Would it be easily possible to fix the order in which methods are output?

**Comment by sizmailov** [comment]
Hi, thanks for the report. Can you share an example of code which reproduces this? Which version of python do you use? 

A PR with extra command line option which makes output in alphabetical order will be very welcome. Not sure when I can get to this myself.
