### ISSUE TITLE
Fully qualified name for enum values seems not appropriate

### ISSUE THREAD

**Issue by tgpfeiffer** [sizmailov/pybind11-stubgen#24]
Consider the following C++ code:
```cpp
namespace pkg {
class Foo {
 public:
  enum FooStatus { kA, kB };
};

enum Bar { kC, kD };
}
```
and the corresponding pybind wrapper code
```cpp
  py::class_<pkg::Foo> foo(m, "Foo");

  py::enum_<pkg::Foo::FooStatus>(foo, "FooStatus")
      .value("A", pkg::Foo::FooStatus::kA)
      .value("B", pkg::Foo::FooStatus::kB)
      .export_values();

  py::enum_<pkg::Bar>(m, "Bar")
      .value("C", pkg::Bar::kC)
      .value("D", pkg::Bar::kD)
      .export_values();
```

This leads to the following generated stub when run with `pybind11-stubgen org.company.pkg`:
```python
class Bar():
    """
    Members:

      C

      D
    """
    def __init__(self, arg0: int) -> None: ...
    def __int__(self) -> int: ...
    @property
    def name(self) -> str:
        """
        (self: handle) -> str

        :type: str
        """
    C: org.company.pkg.Bar # value = Bar.C
    D: org.company.pkg.Bar # value = Bar.D
    __entries: dict # value = {'C': (Bar.C, None), 'D': (Bar.D, None)}
    __members__: dict # value = {'C': Bar.C, 'D': Bar.D}
    pass

class Foo():
    class FooStatus():
        """
        Members:

          A

          B
        """
        def __init__(self, arg0: int) -> None: ...
        def __int__(self) -> int: ...
        @property
        def name(self) -> str:
            """
            (self: handle) -> str

            :type: str
            """
        A: org.company.pkg.FooStatus # value = FooStatus.A
        B: org.company.pkg.FooStatus # value = FooStatus.B
        __entries: dict # value = {'A': (FooStatus.A, None), 'B': (FooStatus.B, None)}
        __members__: dict # value = {'A': FooStatus.A, 'B': FooStatus.B}
        pass
    A: org.company.pkg.FooStatus # value = FooStatus.A
    B: org.company.pkg.FooStatus # value = FooStatus.B
    pass

C: org.company.pkg.Bar # value = Bar.C
D: org.company.pkg.Bar # value = Bar.D
```
and the Python code
```python
from .pkg import Foo, Bar

reveal_type(Foo.FooStatus.A)
reveal_type(Bar.C)
```
when processed with `mypy` shows
```
typetest.py:3: note: Revealed type is 'Any'
typetest.py:4: note: Revealed type is 'Any'

```

When we replace the lines
```python
        A: org.company.pkg.FooStatus # value = FooStatus.A
        B: org.company.pkg.FooStatus # value = FooStatus.B
```
inside `FooStatus` with
```python
        A: Foo.FooStatus # value = FooStatus.A
        B: Foo.FooStatus # value = FooStatus.B
```
and
```python
    C: org.company.pkg.Bar # value = Bar.C
    D: org.company.pkg.Bar # value = Bar.D
```
with
```python
    C: Bar # value = Bar.C
    D: Bar # value = Bar.D
```
then `mypy` shows
```
typetest.py:3: note: Revealed type is 'pkg.Foo.FooStatus'
typetest.py:4: note: Revealed type is 'pkg.Bar'
```

This makes me wonder whether we should not put the fully qualified name of the class behind the colon (in the case of nested enums it's not even correct), but only the `__qualname__`. I can try to attack this, but I would first like to understand the reasoning behind this.

On another note, why are the enum values repeated on one level above their definition? With the code above `C` and `D` become top-level entries of the module, this doesn't seem right.

Yet another related comment: When processing the stub above with `mypy` then it also complains that `dict` should not be used, but a `typing.Dict[K, V]` should be used instead.

**Comment by tgpfeiffer** [comment]
I found out that I'm mixing two issues here.
> typetest.py:3: note: Revealed type is 'Any'

This is a local problem caused by my module setup (namespace packages), it's not a problem of pybind11-stubgen. (I don't understand why we'd want the full name rather than just the local name, though. Still happy to hear about the reasoning for using the full name.)

> A: org.company.pkg.FooStatus

This is indeed a bug, I think, because it does not mention the outer class. I'll prepare a PR for this.

**Comment by sizmailov** [comment]
I agree, full-qualified names *can* be shortened to make every static analysis tool happy. Not sure if full-qualified names actually violate rules for *stubs* (sure it's invalid python3 code since the outer class does not yet exist at the point of the declaration of inner one which can be bypassed by annotating with a string, e.g. `D: "org.company.pkg.Bar"`).
