### ISSUE TITLE
Question: How to use/validate ndarray[...] types?

### ISSUE THREAD

**Issue by tgpfeiffer** [sizmailov/pybind11-stubgen#34]
At the moment, the code generated from pybind11-stubgen (0.6.0) has numpy types like
```
numpy.ndarray[numpy.float64, _Shape[4, 4]]
numpy.ndarray[numpy.int8]
numpy.ndarray[uint8]
numpy.ndarray[float64[3, 1], flags.writeable]
```
but how do I actually put them to use? I have the numpy-stubs (`git+https://github.com/numpy/numpy-stubs.git@c49d2d6875971a669a166ea93ef998911af283a1`) installed, but validating the above results in
```
error: "ndarray" expects no type arguments, but 2 given  [type-arg]
```
for the ndarray parameters and
```
error: Bad number of arguments for type alias, expected: 0, given: 2
```
on the same line (for `_Shape` I guess?).

At the moment I regex the additional type information away before feeding it to numpy, but how is this actually supposed to be used?

**Comment by sizmailov** [comment]
Numpy generics are not supported by mypy and other tools as far as I know. Therefore type & shape information needs to be discarded to use mypy. There is a long-standing issue on mypy https://github.com/python/typing/issues/513. 

Note that numpy-stubs repo is obsolete and stubs are included in main numpy repo.

**Comment by tgpfeiffer** [comment]
> Therefore type & shape information needs to be discarded to use mypy

If that is the case, shouldn't pybind11-stubgen output all occurrences of `numpy.ndarray` without any type and shape information? Or is there some other application where that information can be put to use?

**Comment by sizmailov** [comment]
This is valuable information for users of the library who would navigate to stubs to see signatures (as augmentation to documentation). 

I see it's tedious for automatic checks. I don't mind a command-line flag which would strip extra info from numpy arrays.
