### ISSUE TITLE
__entries and __members__ are untyped for enums

### ISSUE THREAD

**Issue by tgpfeiffer** [sizmailov/pybind11-stubgen#35]
If I have an enumeration that's converted to a stub, the result looks something like
```python
class Foo():
    class Status():
        """
        Members:

          COMPLETE

          PARTIAL

          INVALID
        """
        def __init__(self, arg0: int) -> None: ...
        def __int__(self) -> int: ...
        @property
        def name(self) -> str:
            """
            (self: handle) -> str

            :type: str
            """
        COMPLETE: mypkg.Foo.Status # value = Status.COMPLETE
        INVALID: mypkg.Foo.Status # value = Status.INVALID
        PARTIAL: mypkg.Foo.Status # value = Status.PARTIAL
        __entries: dict # value = {'COMPLETE': (Status.COMPLETE, None), 'PARTIAL': (Status.PARTIAL, None), 'INVALID': (Status.INVALID, None)}
        __members__: dict # value = {'COMPLETE': Status.COMPLETE, 'PARTIAL': Status.PARTIAL, 'INVALID': Status.INVALID}
```
but then mypy complains about
```
error: Implicit generic "Any". Use "typing.Dict" and specify generic parameters
```
for the untyped `dict` lines. Could we make this a `typing.Dict` with appropriate generic parameters instead?

**Comment by sizmailov** [comment]
I don't see why mypy complaints. What is wrong with `Any -> Any` mapping? 

While it's possible to iterate over the dict and infer the type from values, implementing it would be a a rabbit hole. 
The main problem is that values of dict are not enough to infer all the types valid to store. 

> Could we make this a typing.Dict 

Yes

> with appropriate generic parameters instead?

No

In case of enumerations it's a bit special case when we can do better. Probably `__entries` and `__members__` should be discarded from stubs altogether.

**Comment by sizmailov** [comment]
I've discarded `__entries` as an implementation detail of pybind11 enumerations.

`__members__` is a mimic of `enum.Enum.__members__` therefore should be there. Not sure how can it be "fixed". Probably mypy checks can be more permissive?

**Comment by sizmailov** [comment]
I doubt this should be solved with `pybind11-stubgen`, therefore closing.
