### ISSUE TITLE
Some classes in the stub are imported as well

### ISSUE THREAD

**Issue by tgpfeiffer** [sizmailov/pybind11-stubgen#36]
For three of the classes in my generated stub file, I also find `import X` lines at the top of that file. It looks like
```python
import mypkg
import typing
import Bar
import Foo
import Hoge
import datetime
import numpy
__all__ = [
...
"Bar",
"Foo",
"Hoge",
...
]
...
```
mypy fails on the generated file with
```
error: Name 'Bar' already defined (possibly by an import)  [no-redef]
```
I can't find anything that makes these classes "special" or understand why only these three should be mentioned there.

**Comment by sizmailov** [comment]
Can you share a minimal pybind11 snippet to reproduce this? I don't see this behavior with test snippets.

**Comment by sizmailov** [comment]
@tgpfeiffer gentle ping

**Comment by tgpfeiffer** [comment]
Sorry, I think it may take a bit of time for me to come up with a minimal example that reproduces this issue. (Locally we just patch away the additional imports, so it has only medium priority for me.)

Do you want to close the issue and reopen as soon as I can submit a minimal code snippet?

**Comment by sizmailov** [comment]
I don't mind opened issues at time point (we have here just a few). Take your time.

**Comment by virtuald** [comment]
I'm also running into this, will try to track it down.

**Comment by virtuald** [comment]
Ok, this occurs when there's an inner class returned by a function in the outer class:

```c++
class DemoClass {
public:
  struct InnerClass {};

  InnerClass fn() { return InnerClass(); }
};

```
Here's my binding ...

```c++
#include "demo.h"
struct rpybuild_demo_initializer {

  using InnerClass = ::DemoClass::InnerClass;

  py::class_<typename ::DemoClass, std::shared_ptr<typename ::DemoClass>>
      cls_DemoClass;

  py::class_<typename ::DemoClass::InnerClass,
             std::shared_ptr<typename ::DemoClass::InnerClass>>
      cls_InnerClass;

  py::module &m;

  rpybuild_demo_initializer(py::module &m)
      :

        cls_DemoClass(m, "DemoClass"),

        cls_InnerClass(cls_DemoClass, "InnerClass"),

        m(m) {}

  void finish() {

    cls_DemoClass.def(py::init<>())
        .def("fn", &::DemoClass::fn)

        ;

    cls_InnerClass.def(py::init<>());
  }

};
```

You can use the binder class via:

```
rpybuild_demo_initializer rdi(m);
rdi.finish();
```

**Comment by sizmailov** [comment]
@virtuald, thanks for example! 

Probably this would fire when inner class is returned from anywhere (or used as argument) since types are processed as a bare strings and _involved modules_ are "found" by stripping trailing `.Inner`. An index table `fully_qualified_name -> object` might help here, but it doesn't feel like a proper solution and would require one more global. Stateless crawler is not the best design choice I made :( .
