### ISSUE TITLE
skip signature degrading

### ISSUE THREAD

**Issue by ixje** [sizmailov/pybind11-stubgen#38]
I just upgraded to `0.6.2` and am now facing something like this
```
[2020-08-27 11:14:21,239] {__init__.py:55} ERROR - Generated stubs signature is degraded to `(*args, **kwargs) -> Any` for
[2020-08-27 11:14:21,240] {__init__.py:56} ERROR - def __init__(self: neo3vm.ArrayStackItem, reference_counter: neo3vm::ReferenceCounter) -> None: pass
[2020-08-27 11:14:21,240] {__init__.py:57} ERROR -                                                                    ^-- Invalid syntax
```

The general idea is cool, but it would be nice if there is a cli flag to skip this downgrading. For example I do a second pass on the generates stubs to fix these myself.

**Comment by sizmailov** [comment]
Hi! The errors should motivate people to fix/report original binding code problems.

I see the extra flag as ad-hoc solution for those who generate stubs for 3rd-party libraries.

**Comment by ixje** [comment]
> I see the extra flag as ad-hoc solution for those who generate stubs for 3rd-party libraries.

Fair assessment. Note that it is unclear to me if you're open to adding this flag?
I think it can be valuable if the library author isn't willing to provide stubs or is not willing to fix his bindings by way of creating forward references.

**Comment by sizmailov** [comment]
I'll merge it in a minute with a minor changes. I want to add a handy link to pybind11 doc/issue which would describe the problem with C++ signatures in docstrings.

**Comment by sizmailov** [comment]
Ok, such issue / docs paragraph does not exist (yet), can add it later.

**Comment by ixje** [comment]
@sizmailov fwiw; I think this issue describes it https://github.com/pybind/pybind11/issues/2263

**Comment by sizmailov** [comment]
The "forward declaration" technique in Yannick's comment is quite useful. I use it all over the place. This example should be in pybind11 docs though.
