### ISSUE TITLE
subpackage shouldn't show up in `__all__`

### ISSUE THREAD

**Issue by virtuald** [sizmailov/pybind11-stubgen#42]
pylint (as embedded in vscode anyways) flags this as an undefined variable.

If the subpackage is placed in its own package, seems like having it in `__all__` is unnecessary?

**Comment by sizmailov** [comment]
Probably they way I currently populate `__all__` is wrong. I think I need to do smth like this
```python
globals_ = {}
exec("from {} import *".format(module_name), globals_)
all = set(globals_.keys()) - {"__builtins__"}
```

**Comment by sizmailov** [comment]
I think pylint might be confused here due to limited introspection in binary modules. With correct stubs for test project I have no complaints in pycharm. 

At the moment `pybind11-stubs` does not handle properly import of modules under different name (equivalent in python:  `import foo as bar`). This might be cause of some troubles for static analysis.

**Comment by sizmailov** [comment]
Closed in 18334922f8b9d82c202b7b666ab5667884e25cca

**Comment by virtuald** [comment]
Sorry for the delay @sizmailov... but that still causes the same problem. :) A better fix would have been removing just

```patch
-        for m in self.submodules:
-            _all_.append(m.short_name)
```

I think the reason pylint is complaining is that it would be expecting to find this:

```py
__all__ = ['i', 'subpkg']
i: int
subpkg: module
```

And instead you're currently generating:

```py
__all__ = ['i', 'subpkg']
i: int
```

I would expect instead for subpkg to not be in `__all__`, and that it wouldn't be a variable? So for the above example:

```py
__all__ = ['i']
i: int
```

The reason I would expect this is because pybind11-stubgen is going to create a `subpkg/__init__.pyi` anyways, so the typechecker/etc will find that and use that?

**Comment by sizmailov** [comment]
```python
__all__ = ['i', 'subpkg']
i: int = 3
```

This snippet is a fine piece of python code/ pylint (2.6.0) does not report errors on dummy module/submodule setup similar to what you've posted earlier. 
If it's ok for `.py` files, should be ok for `.pyi` as well. I think generated stubs are correct. 

Again, I think it's lack of binary modules introspection or appreciation of stubs in pylint.
