### ISSUE TITLE
Failure when function parameter default value repr isn't valid python

### ISSUE THREAD

**Issue by virtuald** [sizmailov/pybind11-stubgen#44]
```
[2020-09-03 01:39:32,372] {__init__.py:60} ERROR - Generated stubs signature is degraded to `(*args, **kwargs) -> Any` for
[2020-09-03 01:39:32,372] {__init__.py:65} ERROR - def __init__(self: wpilib.controller._controller.trajectory.TrapezoidProfile, constraints: wpilib.controller._controller.trajectory.TrapezoidProfile.Constraints, goal: wpilib.controller._controller.trajectory.TrapezoidProfile.State, initial: wpilib.controller._controller.trajectory.TrapezoidProfile.State = <wpilib.controller._controller.trajectory.TrapezoidProfile.State object at 0x7fc9b00663b0>) -> None: ...
```

If I'm understanding the implementation correctly, it looks like [mypy's stubgen](https://github.com/python/mypy/blob/master/mypy/stubgen.py#L597) will set it to `...`?

Tried it out, looks like I'm right:

```python
class A:
    pass


def foo(x: int = 5):
    pass


def a(a: A = A()):
    pass

```

Resulting generated pyi

```python

from typing import Any

class A: ...

def foo(x: int=...) -> Any: ...
def a(a: A=...) -> Any: ...
```

**Comment by virtuald** [comment]
It is nice to use the pyi for documentation... so It seems to me that the easiest thing would be that if the default value were a basic type (str, int, float, None), then it can stay, otherwise replace it with `...`. The more complex way to go about this would be to try the default value first, and if the AST reports a failure then replace it with `...`.

**Comment by sizmailov** [comment]
I don't like to have many patches to  generate valid pyi from invalid bindings because it makes library authors less eager about fixing their code. 

This particular case is quite common, so I think it deserves attention. 
I think I'll add regex replacement `<\w+(\w+\.) object at 0x[0-9a-f]+>` -> `...` along with error message/emergency stop just as we did for invalid signature case earlier. 

Note: representation of default value in pybind11 can be set via `py::arg_v` (probably you are aware of that).

**Comment by sizmailov** [comment]
Note that pybind allows to supply *arbitrary* string as default value which can break assumptions of any parser. Basically I'm saying that I'm too lazy to implement a invalid-default-values-proof parser :sloth:

**Comment by sizmailov** [comment]
I've partially addressed the issue in 8016a144c09169e512a90c70fb43c83b3d047b24. Is it sufficient?

**Comment by virtuald** [comment]
I actually hadn't ran into `py::arg_v` previously, good to know!

Your test looks sufficient to meet my current needs, but I won't have time to try out my usecase until tonight.

**Comment by sizmailov** [comment]
Ok, I look forward for your findings.

**Comment by virtuald** [comment]
Ha, I had forgotten that you're literally parsing the docstring. Definitely a bit annoying, thank you so much for the effort, it finds my annoying default argument! I've got a few improvements in https://github.com/sizmailov/pybind11-stubgen/pull/45

... it does seem that pybind11 should have some hook to store enough data for someone to generate their own signatures so this parsing wouldn't be necessary. Oh well.

**Comment by sizmailov** [comment]
You are right, it would be nice to have finer control over generated docstrings or may be even annotations at some point :) 
Although I imagine this would require quite amount of code which lowers the chances to become part of pybind in foreseeable future :(

I think this issue can be considered closed.

**Comment by orlandini** [comment]
Hello,

I am facing a similar issue but pybind11-stubgen is not being able to tell me where is the error located. here is the output I get:
```
[2021-02-17 11:48:09,798] {__init__.py:688} DEBUG - Parsing 'module_1' module
[2021-02-17 11:48:09,822] {__init__.py:98} ERROR - Generated stubs signature is degraded to `(*args, **kwargs) -> typing.Any` for
[2021-02-17 11:48:09,823] {__init__.py:98} ERROR - Generated stubs signature is degraded to `(*args, **kwargs) -> typing.Any` for
[2021-02-17 11:48:09,948] {__init__.py:688} DEBUG - Parsing 'module_2' module
```
Any clues on how to locate the issue? I am running pybind11-stubgen version 0.8.6 and pybind11 2.6.0rc3.

**Comment by orlandini** [comment]
I just added
```
logger.log(lvl,function_def_str)
```
after
```
logger.log(lvl, "Generated stubs signature is degraded to `(*args, **kwargs) -> typing.Any` for")
```
 so I can find out which function to blame.

**Comment by sizmailov** [comment]
@orlandini I don't see how it could be. In any scenario the troubling function signature should be printed:

https://github.com/sizmailov/pybind11-stubgen/blob/f14583b1e20df527d52c2acf5626d184153be895/pybind11_stubgen/__init__.py#L93-L103

There is no problems in [CI of latest master](https://travis-ci.com/github/sizmailov/pybind11-stubgen/builds/216761556#L729-L742), so it's not reproduced on current master. 

@orlandini I think it's better to open new issue if you think there is no glitch in your setup.

**Comment by orlandini** [comment]
Thanks @sizmailov . Since this would not occur at all times, I think it would be hard to find a minimal setup to reproduce the problem. In case I do find a consistent way to reproduce it, I will then open a new issue.

**Comment by orlandini** [comment]
@sizmailov I was able to reproduce the issue. It happens when there are parameters without default arguments after parameters with default arguments
```
#include <pybind11/pybind11.h>

int add(int i, int j) {
    return i + j;
}

PYBIND11_MODULE(example, m) {
    m.doc() = "pybind11 example plugin"; // optional module docstring

    m.def("add", &add, "A function which adds two numbers",
          pybind11::arg("i")=1, pybind11::arg("j"));
}
```

results in:
```
[2021-03-04 11:45:12,634] {__init__.py:688} DEBUG - Parsing 'example' module
[2021-03-04 11:45:12,634] {__init__.py:98} ERROR - Generated stubs signature is degraded to `(*args, **kwargs) -> typing.Any` for
[2021-03-04 11:45:12,634] {__init__.py:923} INFO - Useful link: Avoiding C++ types in docstrings:
[2021-03-04 11:45:12,634] {__init__.py:924} INFO -       https://pybind11.readthedocs.io/en/latest/advanced/misc.html#avoiding-cpp-types-in-docstrings
```

I know that this shouldn't be allowed, but I thought you might be interested in it anyway.

**Comment by sizmailov** [comment]
Thanks for finding it, @orlandini!

Should be fixed in master.

**Comment by libiqi** [comment]
Hello,

I am facing a similar issue at version 0.13.0

 {__init__.py:142} ERROR - Generated stubs signature is degraded to `(*args, **kwargs) -> typing.Any` for
 {__init__.py:149} ERROR - def add(a: int = 1, b: int) -> int: ...
{__init__.py:150} ERROR -         ^-- Invalid syntax
