### ISSUE TITLE
Docstring can trigger catastrophic backtracking in regex module

### ISSUE THREAD

**Issue by brokenn** [sizmailov/pybind11-stubgen#51]
Hi

**version:** pybind11_stubgen-0.8.6-py3.7

I've tracked down a particular docstring in a large codebase that hangs pybind11-stubgen during the stub creation. I've simplified it to a (non-realistic) example such as below:

```
def foo(fn):
    """
    foo(fn: Any) -> None
 
    Use-case:
        foo(os.get_handle_inheritable, os.set_handle_inheritable)
    """
    pass
```    

The use-case includes a period and is longer than just a few characters, which I suspect triggers a catastrophic backtracking in matching the regex for balanced parentheses.

Of course I can fix this by modifying the example, or prefacing the use-case with '>>>'.  However, I don't have direct access to the code and believe that bad docstrings shouldn't break pybind11-stubgen.

I wonder if the regex matching function signatures could be made more robust?

Thanks!

**Comment by sizmailov** [comment]
Hi, thanks for the report! 

I know, regex is not the right tool for matching balanced parentheses, it's one of the problems reported in #49. I hope I'll find time to fix this soon. In a meantime you can use docstring preprocessing hook (see example in https://github.com/sizmailov/pybind11-stubgen/issues/49#issuecomment-707311916) to bypass the bug. 

(You need triple back-quotes (```) for block code example)

**Comment by brokenn** [comment]
Thanks, I've used the hook as you suggest to bypass the problem for now.
