### ISSUE TITLE
Issue with callable annotation

### ISSUE THREAD

**Issue by virtuald** [sizmailov/pybind11-stubgen#54]
```
>>> print(fn.__doc__)
fn(a: int, b: int, c: module.C, callback: Optional[Union[Callable[[C, int], bool], Callable[..., int]]], *args) -> D

Documentation for fn
```

In stubgen it gets translated to

```
def fn(a: int, b: int, c: module.C, callback: typing.Optional[typing.Callable[[C, int, ...], bool]], *args) -> D:
```

Whereas it should stay as the original annotation.

**Comment by sizmailov** [comment]
I cannot reproduce this. Are you sure you compare the right things?

**Comment by sizmailov** [comment]
Gentle ping, @virtuald

**Comment by virtuald** [comment]
Oops, sorry, missed the email! Let me try to produce a standalone example for you in a bit.

**Comment by virtuald** [comment]
..and by a bit, I mean this weekend, other priorities came up. I'll put it on my calendar, thanks for the ping!

**Comment by sizmailov** [comment]
one more ping, @virtuald  ;)

**Comment by virtuald** [comment]
... I can't remember where this came up. I'll close for now, sorry about that.
