### ISSUE TITLE
Using pybind11 py::buffer generates unknown type buffer in python

### ISSUE THREAD

**Issue by daltairwalter** [sizmailov/pybind11-stubgen#58]
I have a function that takes a py::buffer as an argument and this creates an unknown type.

def fitPoint(self, arg0: buffer) -> float:

**Comment by sizmailov** [comment]
`pybind11-stubgen` doesn't know anything about *actual* underlying types, it just reads info from docstrings. I don't think there is a reliable way to handle it on stubgen side, other than [monkey-patching docstrings on the fly](https://github.com/sizmailov/pybind11-stubgen/issues/49#issuecomment-707311916).

**Comment by daltairwalter** [comment]
I am not sure what I would patch this to - perhaps Any.  I can probably modify the docstring in the pyd too.

Also, it seems like "buffer" shouldn't be in the docstring and I should take this up with the pybind11 group.
