### ISSUE TITLE
Generating bad types for `py::bool_` and `py::float_`

### ISSUE THREAD

**Issue by alkatar21** [sizmailov/pybind11-stubgen#75]
I use 
```cpp
using PyBaseTypes = std::variant<py::bool_, py::int_, py::float_, py::str, py::bytes, py::object>;
```
Generated then:
```py
typing.Union[bool_, int, float_, str, bytes, object]
```
I would expect:
```py
typing.Union[bool, int, float, str, bytes, object]
```

I'm not quite sure if the fault is here or with pybind11.

bybind11: 2.9.0
pybind11-stubgen: 0.10.5

**Comment by sizmailov** [comment]
Thanks for report. I filed a PR to pybind11: https://github.com/pybind/pybind11/pull/3622. 

At the moment `pybind11-stubgen` does not have fine-grained type processing and operates on whole strings. Therefore the simplest "solution" like plain replacements (e.g. `bool_ -> bool`) on stubgen side might be harmful.

**Comment by sizmailov** [comment]
The PR is merged in pybind11 master. If you are affected by this issue consider updating to latest pybind11 version.
I'm closing this as "won't fix" due to lack readily available solution on stubgen side.
