### ISSUE TITLE
Is it possible to type the iterator?

### ISSUE THREAD

**Issue by alkatar21** [sizmailov/pybind11-stubgen#76]
This is probably more of a question and I don't know where else to ask it right now.

Is it possible to type the iterator?

I don't know if pybind11 doesn't currently offer that in general, if it's because of my possibly specific implementation or if this package just hasn't implemented that so far?

```cpp
class Value
{
public:
  virtual ~Value() = default;
};

class Array : public Value, public std::vector<Value*>
{
public:
  using std::vector<Value*>::vector;
....
};
....
  py::class_<Array, Value>(m, "Array", "")
....
    .def("__iter__", [](Array& array) {
      return py::make_iterator(array.begin(), array.end());
    }, py::keep_alive<0, 1>()); /* Keep vector alive while iterator is used */
```
Generates:
```py
class Array(Value):
    def __iter__(self) -> typing.Iterator: ...
```
Is it possible to generate somethin like the following?
```py
class Array(Value):
    def __iter__(self) -> typing.Iterator[Value]: ...
```

**Comment by sizmailov** [comment]
It's possible to render iterator types, but the changes were not accepted (yet) in upstream pybind11 repo due to introduced overhead:

Attempt 1: https://github.com/pybind/pybind11/pull/2244
Attempt 2: https://github.com/pybind/pybind11/pull/2371
