### ISSUE TITLE
Generate stubs before install myModule

### ISSUE THREAD

**Issue by nyckmaia** [sizmailov/pybind11-stubgen#79]
Hi, I'm a newer in Python stubs.

Today I compile my `C++` code to a `Python Module` using `Pybind11`.
If I understood how it works, to use `pybind11-stubgen` `myModule` **MUST BE already** installed in a Python environment, right?

If yes, so I have to follow these steps below:
- Compile my C++ code to a Python Module (`pybind11`)
- Install this module in the Python environment (Example.: using `setup.py`)
- After that, run `pybind11-stubgen`, get the output files and copy them to the same folder where my module was installed

Right?

I would like to automatize this process and generate the `stubs` BEFORE run my module installation `setup.py`.
If is possible, it will enable to run `setup.py` once and get both `myModule` and `myModuleStubs` installed at the same time.

Question
-----------
Is there a way to do that?

Thank you,

**Comment by sizmailov** [comment]
Hi! 

Thanks for the question. 

> MUST BE already installed in a Python environment, right?

Yes, it must be available, but it might be installed via `pip --install . `, i.e. **without** creating a distribution. This can be an intermediate step of your CI pipeline.

Once stubs are generated, you are can package them for distribution as described in [PEP 561](https://peps.python.org/pep-0561/) (don't forget to include `py.typed` file to indicate that package provides stubs).

 I don't have a simple example of my own projects. But maybe you will [this ci snippet](https://github.com/spotify/pedalboard/blob/5aa02f73a29baa598f9b4c0c6464723db1101fec/.github/workflows/all.yml#L102-L105) that uses `pybind11-stubgen` [wrapper](https://github.com/spotify/pedalboard/blob/5aa02f73a29baa598f9b4c0c6464723db1101fec/scripts/generate_type_stubs_and_docs.py) helpful.
