### ISSUE TITLE
Missing import `datetime` & `numpy`

### ISSUE THREAD

**Issue by OlivierLDff** [sizmailov/pybind11-stubgen#89]
Hi, in generated stub 
* there is a missing `import datatime` when using [chrono](https://pybind11.readthedocs.io/en/stable/advanced/cast/chrono.html)
* there is a missing `import numpy` when using [eigen](https://pybind11.readthedocs.io/en/stable/advanced/cast/eigen.html)

I guess fix should go somewhere in https://github.com/sizmailov/pybind11-stubgen/blob/80f72766c471e4f1c40b4c4d55aec3980919a0fe/pybind11_stubgen/__init__.py#L910-L962

Is is a problem in my library that i forgot to specify something?

Have a nice day, thanks for the library helping me everyday!

**Comment by sizmailov** [comment]
Hi! Thanks for the report!

All the import issues should be resolved with #112
