### ISSUE TITLE
Pybind11 enums are not correctly detected.

### ISSUE THREAD

**Issue by ChrLackner** [sizmailov/pybind11-stubgen#9]
When exporting an enum using pybind11 enum_ template:
``` cpp
py::enum_<ENUM_TYPE> (m, "MyEnum")
.value("val1", VAL1)
.value("val2", VAL2)
.export_values();
```
the stub generator assumes it is a module, the corresponding pyi file has:
``` python
import MyEnum
```
How do you want to classify enums? Using the Python Enum module?
Best
Christopher

**Comment by sizmailov** [comment]
Hi, thanks for reporting!

Which python/pybind11 version do you use? With python3.6+latest pybind11 enum stubs are generated as classes:

```python
class ConsoleBackgroundColor():
    """Members:

  Green

  Yellow

  Blue

  Magenta"""
    def __init__(self, arg0: int) -> None: ...
    def __int__(self) -> int: ...
    @property
    def name(self) -> str:
        """(self: handle) -> str

:type: str"""
    Blue = None # type: cpp_library_bindings.sublibA.ConsoleBackgroundColor # value = ConsoleBackgroundColor.Blue
    Green = None # type: cpp_library_bindings.sublibA.ConsoleBackgroundColor # value = ConsoleBackgroundColor.Green
    Magenta = None # type: cpp_library_bindings.sublibA.ConsoleBackgroundColor # value = ConsoleBackgroundColor.Magenta
    Yellow = None # type: cpp_library_bindings.sublibA.ConsoleBackgroundColor # value = ConsoleBackgroundColor.Yellow
    __entries = None # type: dict # value = {'Green': (ConsoleBackgroundColor.Green, None), 'Yellow': (ConsoleBackgroundColor.Yellow, None), 'Blue': (ConsoleBackgroundColor.Blue, None), 'Magenta': (ConsoleBackgroundColor.Magenta, None)}
    __members__ = None # type: dict # value = {'Green': ConsoleBackgroundColor.Green, 'Yellow': ConsoleBackgroundColor.Yellow, 'Blue': ConsoleBackgroundColor.Blue, 'Magenta': ConsoleBackgroundColor.Magenta}
```

> How do you want to classify enums?

`pybind11-stubgen` does introspection of the python modules, it will generate it as it rendered by pybind11, not more, not less. 

Current master version generates enums with glitches (but still as classes), I'll merge changes to fix that shortly

**Comment by sizmailov** [comment]
I added test to check inspection of enums generated from plain enum and enum class. You can check the resulting stubs here (https://github.com/sizmailov/pybind11-stubgen/blob/master/test/stubs/expected/cpp_library_bindings/sublibA/__init__.pyi)

The test pybind11 project: https://github.com/sizmailov/pybind11-project-example

Enums in C++ code:
https://github.com/sizmailov/pybind11-project-example/blob/master/include/cpp_library/sublibA/ConsoleColors.h

Enums in binding code:
https://github.com/sizmailov/pybind11-project-example/blob/master/cpp_library_bindings/cpp_library.cpp

**Comment by ChrLackner** [comment]
After checking with the latest pybind11 version and upgrading your stubgen the issue seems to be resolved, thanks!
The only thing I still encouter is a lot of warnings:

WARNING - Unknown member __dict__ type : `<class 'mappingproxy'>` 

Best,
Christopher

**Comment by sizmailov** [comment]
Ok, good. Feel free to reopen if you find any issues with enums.
